version: "3.1"

services:

  sa_auth_app:
    container_name: sa_auth_app
    restart: unless-stopped
    env_file: ../.env
    build:
      context: ../
      dockerfile: ./.dockers/Dockerfile
    ports:
      - 8002:8000
    volumes:
      - ../src:/app/src
    depends_on:
      sa_auth_db:
        condition: service_started

  sa_auth_db:
    image: postgres:15.2
    container_name: sa_auth_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sa_auth
      TZ: America/Hermosillo
    volumes:
      - ../DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sa_auth_adminer:
    image: adminer
    container_name: sa_auth_adminer
    environment:
      TZ: America/Hermosillo
      ADMINER_DESIGN: "ng9"
    ports:
      - 8082:8080
    depends_on:
      sa_auth_db:
        condition: service_started